services:
  - type: web
    name: highsky-backend
    env: node
    rootDir: Back-end
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ADMIN_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
